### ISSUE TITLE
Clone v. new repo

### ISSUE THREAD

**Issue by redthor** [doesntmattr/mongodb-migrations#1]
@caciobanu mentions here:
https://github.com/antimattr/mongodb-migrations/issues/16#issuecomment-242758294

To create a new repo rather than clone.

@caciobanu do you mean to remove the fork reference? Is there some other advantage?

**Comment by caciobanu** [comment]
The main advantage I see is that people will not think that this is just a clone of [antimattr/mongodb-migrations](https://github.com/antimattr/mongodb-migrations) and that they should use that instead.

**Comment by redthor** [comment]
thanks. That's fair enough but I have added commentary to the README as well as the github description (see the main page of this repo).

We can also request github disconnect the fork - that'll have the same effect.

**Comment by caciobanu** [comment]
Great! Also, if what is written in https://github.com/antimattr/mongodb-migrations/issues/16#issuecomment-243078792 takes place then all should be fine.
