### ISSUE TITLE
When running `execute` a duplicate key error is thrown

### ISSUE THREAD

**Issue by redthor** [doesntmattr/mongodb-migrations#11]
I'm not sure whether this is the appropriate use case but I use `execute` (on very rare occasions) to run migrations that are re-runnable. The issue is that we get this error:
```
 [MongoDuplicateKeyException]                                                                                                                   
  db.acme.com:27017: E11000 duplicate key error collection: acme.migration_versions index: version dup key: { : "20161117052356" }  
```

I suggest that we either:
* do not bother attempting to insert a migration version (probably not wise)
* do an `upsert` instead to update the date
* create a version like `20161117052356-1` (sounds complicated)

I think the `upsert` option may be the best?

**Comment by caciobanu** [comment]
The current behavior is the desired one. I do not want to accidentally execute the same migration(s) twice (mistakes happen). If you want to re-execute a migration deleting that version from the collection is a better approach.

**Comment by redthor** [comment]
We use `migrate` to run migrations we haven't run. Why would you use `execute`?

**Comment by caciobanu** [comment]
My bad, I was thinking at the wrong command.

I think upsert is fine. Also, I suggest adding a new parameter to the command to force the new behavior and keep the old one by default.

**Comment by redthor** [comment]
I was thinking the same, perhaps:

`--replay`

and you could then use:

`--replay --no-interaction` 

to make it just do its job.

I'll create a PR
