### ISSUE TITLE
2.0 updates

### ISSUE THREAD

**Issue by redthor** [doesntmattr/mongodb-migrations#22]
Suggested updates:

1. [x] Minimum php is 7.1 - update travis yml
1. [x] Drop antimattr/test dependency
1. [x] Update phpunit to 7 (see #20)
1. [x] Switch to `[ ]` array syntax
1. MongoDB Adapter:
   1. [x] Firstly, add "alcaeus/mongo-php-adapter" as a dependency
   1. [x] Secondly, look at removing usage of mongo-php-adapter by using MongoDB base classes
1. [x] Set up code quality tool https://github.com/doesntmattr/mongodb-migrations/issues/23

Complete the changes for the bundle too https://github.com/doesntmattr/mongodb-migrations-bundle

**Comment by redthor** [comment]
@trq @caciobanu - good to hear your thoughts. 
Some comments in https://github.com/doesntmattr/mongodb-migrations/pull/21 relate to this.

Thanks.

**Comment by caciobanu** [comment]
For **number 5** I think that going with the official library from MongoDB https://github.com/mongodb/mongo-php-library would be a better choice as the new Doctrine ODM will use that directly. That would help us integrating the bundle with the new ODM.

**Comment by redthor** [comment]
It turns out that the library uses Doctrine classes exclusively (apart from some unit tests). So the adapter wasn't really required. See the changes in #30

**Comment by redthor** [comment]
I've tested against `dev-master` - good to go on the release.
