### ISSUE TITLE
Set up automated code quality tool

### ISSUE THREAD

**Issue by redthor** [doesntmattr/mongodb-migrations#23]
e.g.
Sonarqube https://www.sonarqube.org/
Sensiolabs Insight https://insight.sensiolabs.com/docs/github/analyze-a-php-library-on-github.html
Scrutinizer https://scrutinizer-ci.com/
CodeClimate https://docs.codeclimate.com/docs/open-source-free

**Comment by trq** [comment]
I think Scrutinizer is a great fit for a php package as it supports a lot of insights out of the box.

**Comment by caciobanu** [comment]
Scrutinzer is fine for me also.
