### ISSUE TITLE
Current state and doctrine/mongodb-odm ^2

### ISSUE THREAD

**Issue by narcoticfresh** [doesntmattr/mongodb-migrations#46]
Hi guys..

I've seen you recently adapted to `\MongoDB\*` classes in many places, switching from the `\Doctrine\*` classes (like for accessing `Connection`s and `Collection`s and so on).

This is perfectly fine - but currently only available in the `master` branch.

Is there any idea/roadmap when this will be (if still work is needed) finalized and tagged? We would like to have a stable tag that use the new `\MongoDB\*` classes.

Thanks so much

**Comment by narcoticfresh** [comment]
@redthor @caciobanu nothing planned currently?

**Comment by marc-jangvs** [comment]
Also still waiting for this. Would be great if it could be released.

**Comment by nkanzari** [comment]
Same here.

**Comment by caciobanu** [comment]
Support has landed in 3.0
