### ISSUE TITLE
Fixing script compatibility issue for MongoDB 4.2

### ISSUE THREAD

**Issue by juhojama** [doesntmattr/mongodb-migrations#52]
Using MongoDB server version newer than 4.2 causes the tool to stop working. Error appears when JavaScript is used to carry on the migrations.

The cause is the removed MongoDB [eval ](https://docs.mongodb.com/manual/reference/method/db.eval/) command used by the tool. 

Stack trace: 

Migration 20210104082001 failed during Execution. Error no such command: '$eval'
In DatabaseCommand.php line 101:
no such command: '$eval'

@redthor is there any change this would be fixed or alternative way to execute javascript via the tool?

**Comment by redthor** [comment]
Ok, I see the call here:
https://github.com/doesntmattr/mongodb-migrations/blob/master/src/AntiMattr/MongoDB/Migrations/Version.php#L275
going over to
https://github.com/mongodb/mongo-php-library/blob/master/src/Database.php#L252

Hmm, unfortunately the following information from MongoDB means we simply cannot support `$eval` and `executeScript()` with MongoDB 4.2 ->
https://developer.mongodb.com/community/forums/t/eval-replacement-in-4-2/2917/2

In your production environment all new migrations will need to use alternative methods.

If you're reconstructing a test or development environment by running through all the migration versions, you could (1) replace each `executeScript` with an alternative or (2) create a snapshot and insert a migration version that represents your last <4.2 migration.

The second option means you can't go "down" below the migration version <4.2 - not that I see people downgrading that much.

**Comment by juhojama** [comment]
I understand. Thanks for the quick reply and good work on the tool.
